# Generated by Django 4.0.4 on 2022-05-11 19:37

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.IntegerField(blank=True)),
                ('proteins', models.IntegerField(blank=True)),
                ('fats', models.IntegerField(blank=True)),
                ('carbohydrates', models.IntegerField(blank=True)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('type_is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название рецепта')),
                ('text', models.TextField(max_length=10000, verbose_name='Текст рецепта')),
                ('cooking_time', models.TimeField(blank=True, default='00:05', verbose_name='Время готовки')),
                ('photo', models.ImageField(blank=True, upload_to='recipes/images', verbose_name='Фото рецепта')),
                ('video', models.FileField(blank=True, upload_to='recipes/videos', verbose_name='Видео рецепта')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Страна происхождения рецепта')),
                ('type', models.CharField(max_length=255, verbose_name='Тип блюда')),
                ('cooking_type', models.CharField(max_length=255, verbose_name='Тип приготовления')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('last_edited_datetime', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('level', models.CharField(max_length=255, verbose_name='Уровень пользователя')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussr.recipe')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ussr.user')),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(blank=True, max_length=255, verbose_name='Количество/Вес')),
                ('is_required', models.BooleanField(verbose_name='Обязательный')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ussr.ingredient')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussr.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussr.recipe')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussr.user')),
            ],
        ),
    ]
