# Generated by Django 4.0.4 on 2022-05-12 15:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ussr', '0002_alter_ingredient_calories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='оценка рецепта от 1 до 10')),
            ],
            options={
                'verbose_name': 'оценка рецепта',
                'verbose_name_plural': 'оценки рецептов',
            },
        ),
        migrations.CreateModel(
            name='ReviewRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rate', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='оценка отзыва от 1 до 10')),
            ],
            options={
                'verbose_name': 'оценка отзыва',
                'verbose_name_plural': 'оценки отзывов',
            },
        ),
        migrations.AlterModelOptions(
            name='bookmarks',
            options={'verbose_name': 'заметка', 'verbose_name_plural': 'заметки'},
        ),
        migrations.AlterModelOptions(
            name='composition',
            options={'verbose_name': 'состав', 'verbose_name_plural': 'составы'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'ингредиент', 'verbose_name_plural': 'ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'рецептик', 'verbose_name_plural': 'рецептики'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='type_is_required',
        ),
        migrations.AddField(
            model_name='composition',
            name='type_is_required',
            field=models.BooleanField(default=False, verbose_name='обязательный тип ингредиента'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='average_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='средняя оценка'),
        ),
        migrations.AddField(
            model_name='review',
            name='average_rate',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='средняя оценка отзыва'),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ussr.ingredient'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='обязательный ингредиент'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='volume',
            field=models.CharField(blank=True, max_length=255, verbose_name='количество / вес'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.FloatField(blank=True, verbose_name='килокалорий на 100г'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbohydrates',
            field=models.FloatField(blank=True, verbose_name='углеводов на 100г'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fats',
            field=models.FloatField(blank=True, verbose_name='жиров на 100г'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='proteins',
            field=models.FloatField(blank=True, verbose_name='белков на 100г'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(blank=True, max_length=255, verbose_name='тип продукта (например, для помидора: "Черри")'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.TimeField(blank=True, default='00:05', verbose_name='время готовки'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_type',
            field=models.CharField(max_length=255, verbose_name='тип приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='country',
            field=models.CharField(blank=True, max_length=255, verbose_name='страна происхождения рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='last_edited_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, upload_to='recipes/images', verbose_name='фото рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(max_length=10000, verbose_name='текст рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(max_length=255, verbose_name='тип блюда'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video',
            field=models.FileField(blank=True, upload_to='recipes/videos', verbose_name='видео рецепта'),
        ),
        migrations.AlterField(
            model_name='review',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussr.recipe', verbose_name='рецепт, на который был оставлен коммент'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ussr.user', verbose_name='пользователь, оставивший отзыв'),
        ),
        migrations.AddConstraint(
            model_name='bookmarks',
            constraint=models.UniqueConstraint(fields=('recipe_id', 'user_id'), name='unique_recipeid-userid_bookmarks'),
        ),
        migrations.AddField(
            model_name='reviewrate',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussr.review', verbose_name='отзыв, на который поставлена оценка'),
        ),
        migrations.AddField(
            model_name='reviewrate',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussr.user', verbose_name='пользователь, поставивший оценку'),
        ),
        migrations.AddField(
            model_name='reciperate',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussr.recipe', verbose_name='рецепт, на который поставлена оценка'),
        ),
        migrations.AddField(
            model_name='reciperate',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussr.user', verbose_name='пользователь, поставивший оценку'),
        ),
        migrations.AddConstraint(
            model_name='reviewrate',
            constraint=models.UniqueConstraint(fields=('review_id', 'user_id'), name='unique_reviewid-userid_reviewrate'),
        ),
        migrations.AddConstraint(
            model_name='reciperate',
            constraint=models.UniqueConstraint(fields=('recipe_id', 'user_id'), name='unique_recipeid-userid_reciperate'),
        ),
    ]
