# Generated by Django 4.0.4 on 2022-05-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ussr', '0005_alter_composition_ingredient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarks',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='bookmarks',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='composition',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='composition',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='reciperate',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='reciperate',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reviewrate',
            old_name='review_id',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='reviewrate',
            old_name='user_id',
            new_name='user',
        ),
    ]
