# Generated by Django 4.0.4 on 2022-05-12 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussr', '0006_rename_recipe_id_bookmarks_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrate',
            name='average_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='оценка отзыва от 1 до 10'),
        ),
    ]
